version: '3.6'

services:
  web:
    volumes:
      - ./:/mirza
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
    ports:
      - '3333:3333'

  postgres:
    image: postgres:12.3-alpine
    restart: always
    env_file:
      - ./common.env
  # hasura:
  #   image: hasura/graphql-engine:v1.3.3
  #   ports:
  #     - '9000:9000'
  #   environment:
  #     HASURA_GRAPHQL_SERVER_PORT: 9000
  #     HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
  #     HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:root@postgres:5432/mirza_development'
  #     HASURA_GRAPHQL_AUTH_HOOK: 'http://web:3333/api/auth/hasura'
  #     HASURA_GRAPHQL_ADMIN_SECRET: 'password'
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
